# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  debian:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: armel

    - name: Build docker image
      run: docker-compose build

    - name: Debootstrap Debian using docker
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register
        # modprobe binfmt_misc
        docker-compose run deboot

    - name: Upload debian
      uses: actions/upload-artifact@v3
      with:
        name: debian
        path: dist/*.final.tar.gz

    - name: Upload kernel files
      uses: actions/upload-artifact@v3
      with:
        name: kernel-images
        path: |
          dist/vmlinuz
          dist/initrd.img
          dist/uImage-*

  # This workflow contains a single job called "build"
  uboot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: armel

    - name: Build docker image
      run: docker-compose build

    - name: Build u-boot using docker
      run: |
        docker-compose run uboot

    - name: Upload u-boot files
      uses: actions/upload-artifact@v3
      with:
        name: u-boot
        path: dist/*
